name: .NET Build Template

on:
  workflow_call:
    inputs:
      dotnet_version:
        type: string
        default: "8.0"
      project_path:
        type: string
        default: "./"

jobs:
  build_dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Restore
        run: dotnet restore ${{ inputs.project_path }}

      - name: Build
        run: dotnet build ${{ inputs.project_path }} --configuration Release

      - name: Test
        run: dotnet test ${{ inputs.project_path }} --no-build --verbosity normal
